//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amirler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Amirler()
        {
            this.Departmanlars = new HashSet<Departmanlar>();
        }
    
        public int amirID { get; set; }
        public string amirTC { get; set; }
        public string amirAdi { get; set; }
        public string amirSoyadi { get; set; }
        public Nullable<int> amirDepartmani { get; set; }
        public Nullable<int> amirMakamAraci { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Makam_Araclari Makam_Araclari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departmanlar> Departmanlars { get; set; }
    }
}
