//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayıtlar
    {
        public int kayıtDosyaID { get; set; }
        public string kayıtDosyaAdi { get; set; }
        public string kayıtDostaTürü { get; set; }
        public Nullable<int> kayıtPersonelID { get; set; }
        public Nullable<int> kayıtDepartmanID { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
