//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makam_Korumalari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makam_Korumalari()
        {
            this.Makam_Araclari = new HashSet<Makam_Araclari>();
        }
    
        public int korumaID { get; set; }
        public string korumaTC { get; set; }
        public string korumaAdi { get; set; }
        public string korumaSoyadi { get; set; }
        public string korumaSehir { get; set; }
        public Nullable<int> korumaSilah { get; set; }
        public Nullable<int> korumaMaas { get; set; }
    
        public virtual Maaslar Maaslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makam_Araclari> Makam_Araclari { get; set; }
        public virtual Silahlar Silahlar { get; set; }
    }
}
