//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceDepartment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliceDepartmantEntities : DbContext
    {
        public PoliceDepartmantEntities()
            : base("name=PoliceDepartmantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amirler> Amirlers { get; set; }
        public virtual DbSet<Bölgeler> Bölgeler { get; set; }
        public virtual DbSet<Departmanlar> Departmanlars { get; set; }
        public virtual DbSet<Ekip_Araclari> Ekip_Araclaris { get; set; }
        public virtual DbSet<Kayıtlar> Kayıtlar { get; set; }
        public virtual DbSet<Maaslar> Maaslars { get; set; }
        public virtual DbSet<Makam_Araclari> Makam_Araclaris { get; set; }
        public virtual DbSet<Makam_Korumalari> Makam_Korumalaris { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
        public virtual DbSet<Primler> Primlers { get; set; }
        public virtual DbSet<Silahlar> Silahlars { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
