//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Kayıtlar = new HashSet<Kayıtlar>();
        }
    
        public int personelID { get; set; }
        public string personelTC { get; set; }
        public string personelAdi { get; set; }
        public string personelSoyadi { get; set; }
        public string personelCinsiyeti { get; set; }
        public string personelSehri { get; set; }
        public Nullable<System.DateTime> personelYas { get; set; }
        public Nullable<int> personelDepartmani { get; set; }
        public Nullable<int> personelBölge { get; set; }
        public Nullable<int> personelArac { get; set; }
        public Nullable<int> personelSilah { get; set; }
        public Nullable<int> personelMaas { get; set; }
        public Nullable<int> personelPrim { get; set; }
    
        public virtual Bölgeler Bölgeler { get; set; }
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Ekip_Araclari Ekip_Araclari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayıtlar> Kayıtlar { get; set; }
        public virtual Maaslar Maaslar { get; set; }
        public virtual Primler Primler { get; set; }
        public virtual Silahlar Silahlar { get; set; }
    }
}
